info:
  contact: {}
  description: Durian HiTech
  title: Durian Covid-19 Golang Backend
  version: "1.0"
paths:
  /:
    get:
      description: 测试 Index 页
      responses:
        "200":
          description: '{"success": true, "message": "gcp"}'
          schema:
            type: string
      tags:
      - 测试
  /data/list_all_high_risk_areas:
    get:
      description: 获取所有中高风险地区，返回列表
      responses:
        "200":
          description: '{"success":true, "message":"查询成功","data":"所有中高风险地区""}'
          schema:
            type: string
      tags:
      - 数据
  /data/query_data:
    post:
      description: 获取在数据库中直接存的 Json File
      parameters:
      - description: 数据文件名
        in: formData
        name: name
        required: true
        type: string
      responses:
        "200":
          description: '{"success":true, "message":"查询失败，无所需数据"}'
          schema:
            type: string
      tags:
      - 数据
  /news/detail:
    post:
      description: 查看单条新闻
      parameters:
      - description: 新闻ID
        in: formData
        name: news_id
        required: true
        type: string
      responses:
        "200":
          description: '{"success":true, "message":"查询成功","data":"该条新闻的详细信息"}'
          schema:
            type: string
        "404":
          description: '{"success":true, "message":"查询失败，新闻ID不存在"}'
          schema:
            type: string
      tags:
      - 新闻
  /news/list_all_news:
    get:
      description: 获取所有新闻，返回列表
      responses:
        "200":
          description: '{"success":true, "message":"查询成功","data":"所有新闻""}'
          schema:
            type: string
      tags:
      - 新闻
  /notice/create_comment:
    post:
      description: 创建一条评论
      parameters:
      - description: 用户ID
        in: formData
        name: user_id
        required: true
        type: string
      - description: 用户类型
        in: formData
        name: user_type
        required: true
        type: string
      - description: 问题ID
        in: formData
        name: question_id
        required: true
        type: string
      - description: 评论内容
        in: formData
        name: comment_content
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "用户评论成功"}'
          schema:
            type: string
        "400":
          description: '{"success": false, "message": "用户ID不存在"}'
          schema:
            type: string
        "401":
          description: '{"success": false, "message": "问题ID不存在"}'
          schema:
            type: string
        "402":
          description: '{"success": false, "message": "评论失败"}'
          schema:
            type: string
      tags:
      - 防控知识板块
  /notice/create_question:
    post:
      description: 创建一个问题
      parameters:
      - description: 用户ID
        in: formData
        name: user_id
        required: true
        type: string
      - description: 提问标题
        in: formData
        name: question_title
        required: true
        type: string
      - description: 提问内容
        in: formData
        name: question_content
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "用户提问成功", "detail": 提问的全部信息}'
          schema:
            type: string
        "401":
          description: '{"success": false, "message": "数据库error, 一些其他错误"}'
          schema:
            type: string
        "404":
          description: '{"success": false, "message": "用户ID不存在"}'
          schema:
            type: string
      tags:
      - 防控知识板块
  /notice/list_all_comments:
    get:
      description: 列出某个问题的全部评论
      parameters:
      - description: 问题ID
        in: formData
        name: question_id
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "查看成功", "data": "某问题的所有评论"}'
          schema:
            type: string
        "404":
          description: '{"success": false, "message": "问题ID不存在"}'
          schema:
            type: string
      tags:
      - 防控知识板块
  /notice/list_all_questions:
    get:
      description: 列出全部问题
      responses:
        "200":
          description: '{"success": true, "message": "查看成功", "data": "全部问题"}'
          schema:
            type: string
      tags:
      - 防控知识板块
  /sub/del_sub:
    post:
      description: 删除订阅
      parameters:
      - description: 订阅ID
        in: formData
        name: subscription_id
        required: true
        type: string
      responses:
        "200":
          description: '{"success":true, "message":"删除成功"}'
          schema:
            type: string
        "401":
          description: '{"success": false, "message": "数据库error, 一些其他错误"}'
          schema:
            type: string
        "404":
          description: '{"success": false, "message": "用户ID不存在"}'
          schema:
            type: string
      tags:
      - 订阅城市
  /sub/list_all_subs:
    post:
      description: 获取订阅列表
      parameters:
      - description: 用户ID
        in: formData
        name: user_id
        required: true
        type: string
      responses:
        "200":
          description: '{"success":true, "message":"查询成功","data":"user的所有订阅"}'
          schema:
            type: string
        "404":
          description: '{"success": false, "message": "用户ID不存在"}'
          schema:
            type: string
      tags:
      - 订阅城市
  /sub/subscribe:
    post:
      description: 订阅城市疫情信息
      parameters:
      - description: 用户ID
        in: formData
        name: user_id
        required: true
        type: string
      - description: 城市名字
        in: formData
        name: city_name
        required: true
        type: string
      responses:
        "200":
          description: '{"success": false, "message": "已经订阅过这个城市的疫情信息"}'
          schema:
            type: string
        "401":
          description: '{"success": false, "message": "数据库error, 一些其他错误"}'
          schema:
            type: string
        "404":
          description: '{"success": false, "message": "用户ID不存在"}'
          schema:
            type: string
      tags:
      - 订阅城市
  /user/info:
    post:
      description: 查看用户个人信息
      parameters:
      - description: 用户ID
        in: formData
        name: user_id
        required: true
        type: string
      responses:
        "200":
          description: '{"success": true, "message": "查看用户信息成功", "data": "model.User的所有信息"}'
          schema:
            type: string
        "404":
          description: '{"success": false, "message": "用户ID不存在"}'
          schema:
            type: string
      tags:
      - 用户管理
  /user/login:
    post:
      description: 登录
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      responses:
        "200":
          description: '{"success": false, "message": "没有该用户"}'
          schema:
            type: string
      tags:
      - 用户管理
  /user/modify:
    post:
      description: 修改用户信息（支持修改用户名和密码）
      parameters:
      - description: 用户ID
        in: formData
        name: user_id
        required: true
        type: string
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 原密码
        in: formData
        name: password_old
        required: true
        type: string
      - description: 新密码
        in: formData
        name: password_new
        required: true
        type: string
      responses:
        "200":
          description: '{"success": false, "message": "用户ID不存在"}'
          schema:
            type: string
        "400":
          description: '{"success": false, "message": "数据库操作时的其他错误"}'
          schema:
            type: string
      tags:
      - 用户管理
  /user/register:
    post:
      description: 注册
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      - description: '用户类型（0: 普通用户，1: 认证机构用户）'
        in: formData
        name: user_type
        required: true
        type: string
      - description: 认证机构名
        in: formData
        name: affiliation
        type: string
      responses:
        "200":
          description: '{"success": false, "message": "用户已存在"}'
          schema:
            type: string
      tags:
      - 用户管理
schemes:
- http
- https
swagger: "2.0"
